dist: trusty

language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea
  - openjdk8
  - openjdk11
  - openjdk-ea
sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

script: mvn clean compile test verify

after_success:
  - mvn jacoco:report coveralls:report
